http POST localhost:8080/post \
userId=1 \
content="This is Content" \
state=PUBLIC

http PATCH localhost:8080/post/1 \
userId=1 \
content="This is Content2" \
state=PUBLIC

http POST localhost:8080/comment \
postId=1 \
userId=1 \
content="커멘트"

http PATCH localhost:8080/comment/1 \
userId=1 \
content="커멘트2"

http POST localhost:8080/post/like \
targetId=1 \
userId=2

http POST localhost:8080/post/unlike \
targetId=1 \
userId=3

http POST localhost:8080/comment/like \
targetId=1 \
userId=2

http POST localhost:8080/comment/unlike \
targetId=1 \
userId=2
