version: '3.8'

services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    networks:
      - my_network

networks:
  my_network:
